### ISSUE TITLE
SteelDroid cannot tell differences between licenses

### ISSUE THREAD

**Issue by AnimbusDev** [SteelDroid/Alex_Cruz_is_a_TROLL__LMFAO#1]
@chevycam94

**Comment by AnimbusDev** [comment]
@chevycam94

**Comment by AnimbusDev** [comment]
Added an update to readme.MD #2

**Comment by Burnergames** [comment]
*StealDroid

**Comment by Mazda--** [comment]
Better watch out, he'll report you to GIT hahaha

**Comment by AnimbusDev** [comment]
@Mazda-- Anything but GIT!

**Comment by chevycam94** [comment]
I'm not going anywhere.  I see I made you butthurt.  Lol

**Comment by Mazda--** [comment]
Still waiting on these 3 teams that supposedly you got coming at me hahahaha

#Kangers #KangBang #StealingAvatarsSince2002
